# Generated by Django 2.2 on 2021-02-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_coupon_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coupon',
            field=models.CharField(default='TRYNEW', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='coupon_amount',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
