# Generated by Django 2.2 on 2021-02-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210224_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='coupon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='coupon_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
