# Generated by Django 2.2 on 2021-02-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210224_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='None', max_length=20),
            preserve_default=False,
        ),
    ]
